// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full p-20\"><div class=\"flex flex-row gap-2 items-center w-full rounded-md shadow-md hover:bg-slate-900 transition duration-300 cursor-pointer\"><h3 class=\"text-2xl\">About</h3></div><h1 class=\"text-3xl mb-2\">Welcome to NEXUS</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque condimentum sapien id scelerisque ullamcorper. Aliquam cursus rhoncus nibh, et iaculis leo blandit luctus. Mauris et pellentesque enim, vel finibus augue. Duis aliquam luctus rhoncus. Curabitur sed ligula in ante iaculis hendrerit vel eu ipsum. Maecenas interdum est ut placerat ultricies. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam quam ligula, viverra et luctus sed, accumsan non erat. Curabitur convallis semper mattis. Vivamus maximus quam non semper feugiat. Proin non varius ex. Mauris finibus ligula a leo laoreet tristique. Ut pretium commodo interdum. Nam nibh leo, posuere ut mi vel, iaculis ultrices sapien. Pellentesque id iaculis orci. Phasellus nisl mauris, accumsan nec turpis a, aliquam imperdiet ligula. Fusce molestie dolor nisl, quis pellentesque dui malesuada nec. Maecenas cursus rhoncus ipsum, a cursus eros mattis in. Maecenas mattis efficitur laoreet. Fusce interdum nec nulla ac tempor. Donec placerat nisl mi, sed venenatis nunc faucibus id. Praesent aliquam dolor mauris, vel faucibus sem scelerisque sed. Aenean dui orci, egestas quis est eget, iaculis tempor felis. Curabitur et ex ut velit pellentesque scelerisque in id lacus. Mauris laoreet est vel nisl eleifend, vel sodales odio hendrerit.</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
