// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Pradhyumna-Joshi/go_mcp_frontend/models"

func ConfigMain(conf []models.ModelConfig) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full h-screen flex flex-col overflow-hidden p-20\"><div class=\"flex flex-row gap-2 pb-2 items-center w-full rounded-md shadow-md transition duration-300 cursor-pointer\"><h3 class=\"text-3xl select-none\">Configuration</h3></div><div class=\"flex-1 overflow-y-auto scroll-smooth\"><div class=\"mt-8\"><h1 class=\"text-xl font-bold\">Planner LLM</h1><p class=\"mt-2 text-sm italic\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque condimentum sapien id scelerisque ullamcorper. Aliquam cursus rhoncus nibh, et iaculis leo blandit luctus. Mauris et pellentesque enim, vel finibus augue. Duis aliquam luctus rhoncus. Curabitur sed ligula in ante iaculis hendrerit vel eu ipsum. Maecenas interdum est ut placerat ultricies. Interdum et malesuada fames ac ante ipsum primis in faucibus</p><form hx-post=\"/setmodelconf\" hx-target=\"#result\" hx-swap=\"innerHTML\" class=\"w-full flex flex-col gap-4 items-start justify-center mt-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Input(models.Input{
			Label:       "Name",
			Name:        "name1",
			Value:       conf[0].Name,
			Type:        "text",
			Title:       "Name",
			Required:    true,
			PlaceHolder: "groq-gpt-oss-120b",
			ClassName:   "focus:border-blue-500",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Input(models.Input{
			Label:       "Provider",
			Name:        "provider1",
			Value:       conf[0].Provider,
			Type:        "text",
			Title:       "Provider",
			PlaceHolder: "openai",
			ClassName:   "focus:border-blue-500",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Input(models.Input{
			Label:       "Base URL",
			Name:        "base_url1",
			Value:       conf[0].BaseURL,
			Type:        "text",
			Title:       "Base URL",
			PlaceHolder: "https://api.groq.com/openai/v1",
			ClassName:   "focus:border-blue-500",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Input(models.Input{
			Label:     "API Key/ Token",
			Name:      "api_key1",
			Value:     conf[0].APIKey,
			Type:      "password",
			Title:     "API Key/ Token",
			ClassName: "focus:border-blue-500",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Input(models.Input{
			Label:       "Model",
			Name:        "model1",
			Value:       conf[0].Model,
			Type:        "text",
			Title:       "Model",
			PlaceHolder: "openai/gpt-oss-120b",
			ClassName:   "focus:border-blue-500",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"mt-8\"><h1 class=\"text-xl font-bold\">Executor LLM</h1><p class=\"mt-2 text-sm italic\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque condimentum sapien id scelerisque ullamcorper. Aliquam cursus rhoncus nibh, et iaculis leo blandit luctus. Mauris et pellentesque enim, vel finibus augue. Duis aliquam luctus rhoncus. Curabitur sed ligula in ante iaculis hendrerit vel eu ipsum. Maecenas interdum est ut placerat ultricies. Interdum et malesuada fames ac ante ipsum primis in faucibus</p><div class=\"w-full flex flex-col gap-4 items-start justify-center mt-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Input(models.Input{
			Label:       "Name",
			Name:        "name2",
			Value:       conf[1].Name,
			Type:        "text",
			Title:       "Name",
			Required:    true,
			PlaceHolder: "groq-gpt-oss-120b",
			ClassName:   "focus:border-blue-500",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Input(models.Input{
			Label:       "Provider",
			Name:        "provider2",
			Value:       conf[1].Provider,
			Type:        "text",
			Title:       "Provider",
			PlaceHolder: "openai",
			ClassName:   "focus:border-blue-500",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Input(models.Input{
			Label:       "Base URL",
			Name:        "base_url2",
			Value:       conf[1].BaseURL,
			Type:        "text",
			Title:       "Base URL",
			PlaceHolder: "https://api.groq.com/openai/v1",
			ClassName:   "focus:border-blue-500",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Input(models.Input{
			Label:     "API Key/ Token",
			Name:      "api_key2",
			Value:     conf[1].APIKey,
			Type:      "password",
			Title:     "API Key/ Token",
			ClassName: "focus:border-blue-500",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Input(models.Input{
			Label:       "Model",
			Name:        "model2",
			Value:       conf[1].Model,
			Type:        "text",
			Title:       "Model",
			PlaceHolder: "openai/gpt-oss-120b",
			ClassName:   "focus:border-blue-500",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Button(models.Button{
			Id:        "btn-model-save",
			Type:      "submit",
			Content:   "Save Configuration",
			ClassName: "bg-blue-600 hover:bg-blue-600/80",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div></form></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
