// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Pradhyumna-Joshi/go_mcp_frontend/models"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex w-full max-h-screen\"><div class=\"w-1/3 p-20 h-screen flex flex-col justify-center text-gray-300\"><div class=\"my-4\"><h1 class=\"text-2xl\">Login</h1><p class=\"text-sm italic\">Please login to continue using the app </p></div><form hx-post=\"/login\" hx-target=\"#app\" hx-swap=\"innerHTML\" class=\"w-full flex flex-col gap-5 justify-center\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Input(models.Input{
				Name:        "username",
				Label:       "Username",
				Value:       "",
				Type:        "text",
				Title:       "Username",
				Required:    true,
				PlaceHolder: "eg. john.doe@gmail.com",
				ClassName:   "align-center w-full focus:border-blue-500",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Input(models.Input{
				Name:        "password",
				Label:       "Password",
				Value:       "",
				Type:        "password",
				Title:       "Password",
				PlaceHolder: "Password",
				Required:    true,
				ClassName:   "align-center w-full focus:border-blue-500",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<h1 class=\"w-full text-sm text-center select-none text-white/30\">Don't have an account? <span class=\"underline italic text-blue-600 hover:text-blue-600/80 cursor-pointer\">Sign Up</span></h1>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Button(models.Button{
				Id:        "btn-login",
				Type:      "submit",
				Content:   "Login ",
				ClassName: "w-full bg-blue-600 hover:bg-blue-600/80",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</form></div><div class=\"bg-slate-900 h-screen w-[2px]\"></div><div class=\"w-2/3 h-screen\"><div class=\"p-20 text-gray-300\"><div class=\"mb-5\"><h1 class=\"text-8xl\">NEXUS</h1></div><p class=\"text-sm\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque condimentum sapien id scelerisque ullamcorper. Aliquam cursus rhoncus nibh, et iaculis leo blandit luctus. Mauris et pellentesque enim, vel finibus augue. Duis aliquam luctus rhoncus. Curabitur sed ligula in ante iaculis hendrerit vel eu ipsum. Maecenas interdum est ut placerat ultricies. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam quam ligula, viverra et luctus sed, accumsan non erat. Curabitur convallis semper mattis. Vivamus maximus quam non semper feugiat. Proin non varius ex. Mauris finibus ligula a leo laoreet tristique. Ut pretium commodo interdum. Nam nibh leo, posuere ut mi vel, iaculis ultrices sapien. Pellentesque id iaculis orci. Phasellus nisl mauris, accumsan nec turpis a, aliquam imperdiet ligula. Fusce molestie dolor nisl, quis pellentesque dui malesuada nec. Maecenas cursus rhoncus ipsum, a cursus eros mattis in. Maecenas mattis efficitur laoreet. Fusce interdum nec nulla ac tempor. Donec placerat nisl mi, sed venenatis nunc faucibus id. Praesent aliquam dolor mauris, vel faucibus sem scelerisque sed. Aenean dui orci, egestas quis est eget, iaculis tempor felis. Curabitur et ex ut velit pellentesque scelerisque in id lacus. Mauris laoreet est vel nisl eleifend, vel sodales odio hendrerit.</p></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
